language: c++
dist: focal

env:
  global:
    - CPPLINT_FILTERS='--filter=-readability/casting,-legal/copyright,-build/include_subdir,-whitespace/line_length'
    - CPPLINT_FILES='--recursive src/ include/ test/ main.c'

addons:
   apt:
     packages:
      - python3
      - python3-pip
      - cppcheck
      - gcc
      - g++

compiler:
   - g++

script:
   - pip3 install --user cpplint
   - cpplint $CPPLINT_FILTERS $CPPLINT_FILES
   - sudo apt install postgresql postgresql-contrib
   - sudo systemctl start postgresql@12-main
   - pg_ctlcluster 12 main start
   - sudo apt-get install libpq-dev
   - sudo apt-get install -f libboost-all-dev
   - wget https://github.com/pantor/inja/archive/refs/tags/v3.2.0.tar.gz
   - tar -xvzf v3.2.0.tar.gz
   - cd inja-3.2.0/test/ && rm test.cpp && echo "int main() { return 0; }" >> test.cpp
   - rm benchmark.cpp && echo "int main() { return 0; }" >> benchmark.cpp && cd ..
   - cmake . && make && sudo make install && cd ..
   - wget https://github.com/nlohmann/json/archive/refs/tags/v3.9.1.tar.gz
   - tar -xvzf v3.9.1.tar.gz
   - cd json-3.9.1 && cmake . && make && sudo make install && cd ..
   - cppcheck .
   - sudo apt install curl
   - sudo apt-get install libcurl4-openssl-dev
   - cmake . && sudo make studpark
